### ISSUE TITLE
Actividad 9 Hilos en Windows Form

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-team-ola#1]
[actividad 9 hilos a nuestro proyecto.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-team-ola/files/15132259/actividad.9.hilos.a.nuestro.proyecto.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 18.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
